{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: backend-fernet-key
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "lolday.labels" . | nindent 4 }}
type: Opaque
stringData:
  key: {{ required "backend.fernetKey is required" .Values.backend.fernetKey | quote }}
{{- end }}
