{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: backend-harbor-admin
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "lolday.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "backend.harborAdminPassword is required" .Values.backend.harborAdminPassword | quote }}
{{- end }}
