{{- if .Values.mlflow.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-db
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  username: {{ .Values.mlflow.db.username | quote }}
  password: {{ required "mlflow.db.password must be set via --set" .Values.mlflow.db.password | quote }}
  database: {{ .Values.mlflow.db.database | quote }}
{{- end }}
