{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "lolday.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames: [kube-system]
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  endpoints:
    - targetPort: 9100
      path: /metrics
      interval: 30s
{{- end }}
