{{- if and .Values.monitoring.enabled .Values.monitoring.postgresExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "lolday.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames: [{{ .Values.global.namespace }}]
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
{{- end }}
