apiVersion: v2
name: lolday
description: ISLab Malware Detector Management Platform
type: application
version: 0.3.0
appVersion: "0.3.0"

dependencies:
  - name: harbor
    version: "1.16.1"
    repository: https://helm.goharbor.io
    condition: harbor.enabled
