"""add detector tables

Revision ID: f5c431c00187
Revises:
Create Date: 2026-04-14 11:53:18.154556

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy.generics
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5c431c00187'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('role', sa.Enum('ADMIN', 'DEVELOPER', 'USER', name='role_enum'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('detector',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('git_url', sa.String(length=500), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('detector_owner_git_unique', 'detector', ['owner_id', 'git_url'], unique=True,
                    postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('user_git_credential',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('github', 'gitlab', name='git_provider'), nullable=False),
    sa.Column('encrypted_token', sa.LargeBinary(), nullable=False),
    sa.Column('token_hint', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('detector_build',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detector_id', sa.UUID(), nullable=False),
    sa.Column('git_tag', sa.String(length=100), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('triggered_by_id', sa.UUID(), nullable=False),
    sa.Column('k8s_job_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'cloning', 'validating', 'building', 'scanning', 'succeeded', 'failed', 'timeout', 'cancelled', 'cve_blocked', name='detector_build_status'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('log_tail', sa.Text(), nullable=True),
    sa.Column('trivy_critical', sa.Integer(), nullable=True),
    sa.Column('trivy_high', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['detector_id'], ['detector.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detector_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detector_id', sa.UUID(), nullable=False),
    sa.Column('git_tag', sa.String(length=100), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=False),
    sa.Column('harbor_image', sa.String(length=500), nullable=False),
    sa.Column('image_digest', sa.String(length=100), nullable=False),
    sa.Column('config_schema', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('active', 'retention_pruned', name='detector_version_status'), nullable=False),
    sa.ForeignKeyConstraint(['detector_id'], ['detector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detector_id', 'git_tag', name='detector_version_tag_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detector_version')
    op.drop_table('detector_build')
    op.drop_table('user_git_credential')
    op.drop_index('detector_owner_git_unique', table_name='detector',
                  postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('detector')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    sa.Enum(name='detector_build_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='detector_version_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='git_provider').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
