"""phase7_5_baseline

Revision ID: d3f179666394
Revises: 
Create Date: 2026-04-21 11:37:42.794732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3f179666394'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('train', 'evaluate', 'predict', name='job_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'preparing', 'running', 'succeeded', 'failed', 'cancelled', 'timeout', name='job_status_enum'), nullable=False),
    sa.Column('detector_version_id', sa.UUID(), nullable=False),
    sa.Column('train_dataset_id', sa.Uuid(), nullable=True),
    sa.Column('test_dataset_id', sa.Uuid(), nullable=True),
    sa.Column('predict_dataset_id', sa.Uuid(), nullable=True),
    sa.Column('source_model_version_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('resolved_config', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('mlflow_experiment_id', sa.String(length=50), nullable=True),
    sa.Column('mlflow_run_id', sa.String(length=50), nullable=True),
    sa.Column('k8s_job_name', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('log_tail', sa.Text(), nullable=True),
    sa.Column('summary_metrics', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('resource_profile', sa.Enum('standard', name='resource_profile_enum'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['detector_version_id'], ['detector_version.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['predict_dataset_id'], ['dataset_config.id'], ),
    sa.ForeignKeyConstraint(['source_model_version_id'], ['model_version.id'], ),
    sa.ForeignKeyConstraint(['test_dataset_id'], ['dataset_config.id'], ),
    sa.ForeignKeyConstraint(['train_dataset_id'], ['dataset_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_detector_version', 'job', ['detector_version_id'], unique=False)
    op.create_index('ix_job_idempotency', 'job', ['idempotency_key', 'submitted_at'], unique=False)
    op.create_index('ix_job_in_flight', 'job', ['status'], unique=False, postgresql_where="status IN ('pending'::job_status_enum, 'preparing'::job_status_enum, 'running'::job_status_enum)", sqlite_where=None)
    op.create_index('ix_job_owner_submitted', 'job', ['owner_id', 'submitted_at'], unique=False)
    op.create_table('model_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mlflow_name', sa.String(length=200), nullable=False),
    sa.Column('mlflow_version', sa.Integer(), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.Enum('None', 'Staging', 'Production', 'Archived', name='model_stage_enum'), nullable=False),
    sa.Column('detector_version_id', sa.UUID(), nullable=False),
    sa.Column('source_job_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_transitioned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['detector_version_id'], ['detector_version.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['source_job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_version_name_version_unique', 'model_version', ['mlflow_name', 'mlflow_version'], unique=True)
    op.create_index('ix_model_version_owner', 'model_version', ['owner_id'], unique=False)
    op.create_index('ix_model_version_stage', 'model_version', ['current_stage'], unique=False)
    op.create_table('user',
    sa.Column('role', sa.Enum('ADMIN', 'DEVELOPER', 'USER', name='role_enum'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('discord_user_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('dataset_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'private', name='dataset_visibility_enum'), nullable=False),
    sa.Column('csv_content', sa.Text(), nullable=False),
    sa.Column('csv_checksum', sa.String(length=64), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('label_distribution', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('family_distribution', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dataset_config_owner', 'dataset_config', ['owner_id'], unique=False)
    op.create_index('ix_dataset_config_owner_name_unique', 'dataset_config', ['owner_id', 'name'], unique=True, postgresql_where='deleted_at IS NULL', sqlite_where=None)
    op.create_index('ix_dataset_config_visibility', 'dataset_config', ['visibility'], unique=False)
    op.create_table('detector',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('git_url', sa.String(length=500), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('detector_owner_git_unique', 'detector', ['owner_id', 'git_url'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('model_transition_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage', sa.Enum('None', 'Staging', 'Production', 'Archived', name='model_stage_enum'), nullable=False),
    sa.Column('to_stage', sa.Enum('None', 'Staging', 'Production', 'Archived', name='model_stage_enum'), nullable=False),
    sa.Column('actor_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('transitioned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_transition_version', 'model_transition_log', ['model_version_id'], unique=False)
    op.create_table('user_git_credential',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('github', 'gitlab', name='git_provider'), nullable=False),
    sa.Column('encrypted_token', sa.LargeBinary(), nullable=False),
    sa.Column('token_hint', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('detector_build',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detector_id', sa.UUID(), nullable=False),
    sa.Column('git_tag', sa.String(length=100), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('triggered_by_id', sa.UUID(), nullable=False),
    sa.Column('k8s_job_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'cloning', 'validating', 'building', 'scanning', 'succeeded', 'failed', 'timeout', 'cancelled', 'cve_blocked', name='detector_build_status'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('log_tail', sa.Text(), nullable=True),
    sa.Column('trivy_critical', sa.Integer(), nullable=True),
    sa.Column('trivy_high', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('build_token', sa.String(length=80), nullable=True),
    sa.Column('pending_schema', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['detector_id'], ['detector.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detector_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detector_id', sa.UUID(), nullable=False),
    sa.Column('git_tag', sa.String(length=100), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=False),
    sa.Column('harbor_image', sa.String(length=500), nullable=False),
    sa.Column('image_digest', sa.String(length=100), nullable=False),
    sa.Column('config_schema', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('mlflow_experiment_id', sa.String(length=50), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('active', 'retention_pruned', name='detector_version_status'), nullable=False),
    sa.ForeignKeyConstraint(['detector_id'], ['detector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detector_id', 'git_tag', name='detector_version_tag_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detector_version')
    op.drop_table('detector_build')
    op.drop_table('user_git_credential')
    op.drop_index('ix_model_transition_version', table_name='model_transition_log')
    op.drop_table('model_transition_log')
    op.drop_index('detector_owner_git_unique', table_name='detector', postgresql_where='deleted_at IS NULL')
    op.drop_table('detector')
    op.drop_index('ix_dataset_config_visibility', table_name='dataset_config')
    op.drop_index('ix_dataset_config_owner_name_unique', table_name='dataset_config', postgresql_where='deleted_at IS NULL', sqlite_where=None)
    op.drop_index('ix_dataset_config_owner', table_name='dataset_config')
    op.drop_table('dataset_config')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index('ix_model_version_stage', table_name='model_version')
    op.drop_index('ix_model_version_owner', table_name='model_version')
    op.drop_index('ix_model_version_name_version_unique', table_name='model_version')
    op.drop_table('model_version')
    op.drop_index('ix_job_owner_submitted', table_name='job')
    op.drop_index('ix_job_in_flight', table_name='job', postgresql_where="status IN ('pending'::job_status_enum, 'preparing'::job_status_enum, 'running'::job_status_enum)", sqlite_where=None)
    op.drop_index('ix_job_idempotency', table_name='job')
    op.drop_index('ix_job_detector_version', table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
