name: helpers

on:
  push:
    branches: [main]
    paths:
      - "charts/lolday/helpers/build-helper/**"
      - "charts/lolday/helpers/job-helper/**"
      - ".github/workflows/helpers.yml"
      - ".github/actions/docker-meta-build/**"
  pull_request:
    branches: [main]
    paths:
      - "charts/lolday/helpers/build-helper/**"
      - "charts/lolday/helpers/job-helper/**"
      - ".github/workflows/helpers.yml"
      - ".github/actions/docker-meta-build/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-helper:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        helper: [build-helper, job-helper]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build (and push if not PR)
        uses: ./.github/actions/docker-meta-build
        with:
          image: lolday-${{ matrix.helper }}
          context: ./charts/lolday/helpers/${{ matrix.helper }}
          push: ${{ github.event_name != 'pull_request' }}
