name: images

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/images.yml"
      - ".github/actions/docker-meta-build/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/images.yml"
      - ".github/actions/docker-meta-build/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write # H-23: cosign keyless OIDC flow needs this at job scope
    strategy:
      fail-fast: false
      matrix:
        image: [backend, frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build (and push if not PR)
        uses: ./.github/actions/docker-meta-build
        with:
          image: lolday-${{ matrix.image }}
          context: ./${{ matrix.image }}
          push: ${{ github.event_name != 'pull_request' }}
